### ISSUE TITLE
Different operations in Attention Layer with official code

### ISSUE THREAD

**Issue by DongjunLee** [jojonki/BiDAF#11]
Hi @jojonki,
Your code is very clear, so it was very helpful.

I figure out some different operation with [official code](https://github.com/allenai/bi-att-flow).

- your code
```python
# Context2Query
        c2q = torch.bmm(F.softmax(S, dim=-1), embd_query) # (N, T, 2d) = bmm( (N, T, J), (N, J, 2d) )
```

- official code

u_logits == S

```python
# Context2Query
u_a = softsel(u_aug, u_logits)  # [N, M, JX, d]
```

I checked [softsel](https://github.com/allenai/bi-att-flow/blob/master/my/tensorflow/nn.py#L50) function in offical code.

This operation is contain element-wise multiplication, but the operation in your code is `torch.bmm` 
(batch matrix-matrix multiplication). (same as Query2Context part)

I think this operation may be the reason of issue #1 .

**Comment by jojonki** [comment]
Hi. Thank you for your comment.

Now, I do not have time to check the code. Could you try it? If this is the reason for #1, that would be nice. Pull-request is also welcomed 👍

**Comment by aneesh-joshi** [comment]
Any updates @DongjunLee ?

**Comment by DongjunLee** [comment]
I also don't have time to update.
@aneesh-joshi, I recommend to check [allennlp's bidaf model](https://github.com/allenai/allennlp/blob/master/allennlp/models/reading_comprehension/bidaf.py) codes.
